Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
maca: real
quantidade: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(" digite a quantidade que voce quer comprar ")
leia(quantidade)



Fimalgoritmo